// Code generated by "stringer -type=Type -trimprefix=Type -linecomment"; DO NOT EDIT.

package format

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeCSV-0]
	_ = x[TypeAVRO-1]
}

const _Type_name = "CSVAVRO"

var _Type_index = [...]uint8{0, 3, 7}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
