// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package destination

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"snowflake.csvGoroutines": {
			Default:     "1",
			Description: "For CSV processing, the number of goroutines to concurrently process CSV rows.",
			Type:        sdk.ParameterTypeInt,
			Validations: []sdk.Validation{},
		},
		"snowflake.fileUploadThreads": {
			Default:     "30",
			Description: "Number of threads to run for PUT file uploads.",
			Type:        sdk.ParameterTypeInt,
			Validations: []sdk.Validation{},
		},
		"snowflake.format": {
			Default:     "",
			Description: "Data type of file we upload and copy data from to snowflake",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
				sdk.ValidationInclusion{List: []string{"csv", "avro"}},
			},
		},
		"snowflake.namingPrefix": {
			Default:     "meroxa",
			Description: "Prefix to append to update_at , deleted_at, create_at at destination table",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"snowflake.primaryKey": {
			Default:     "",
			Description: "Primary key of the source table",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"snowflake.stage": {
			Default:     "0",
			Description: "Snowflake snowflake.stage data is copied into before merge",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"snowflake.table": {
			Default:     "",
			Description: "snowflake.table name.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"snowflake.url": {
			Default:     "",
			Description: "snowflake.url string connection to snowflake DB. Detail information https://pkg.go.dev/github.com/snowflakedb/gosnowflake@v1.6.9#hdr-snowflake.url_String",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
