// Code generated by MockGen. DO NOT EDIT.
// Source: destination.go
//
// Generated by this command:
//
//	mockgen -source=destination.go -destination mock/destination_mock.go . writer.Writer
//

// Package mock_destination is a generated GoMock package.
package mock_destination
