// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package source

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigSnowflakeBatchsize      = "snowflake.batchsize"
	ConfigSnowflakeColumns        = "snowflake.columns"
	ConfigSnowflakeOrderingColumn = "snowflake.orderingColumn"
	ConfigSnowflakePrimaryKeys    = "snowflake.primaryKeys"
	ConfigSnowflakeSnapshot       = "snowflake.snapshot"
	ConfigSnowflakeTable          = "snowflake.table"
	ConfigSnowflakeUrl            = "snowflake.url"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigSnowflakeBatchsize: {
			Default:     "100",
			Description: "BatchSize - size of batch.",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{},
		},
		ConfigSnowflakeColumns: {
			Default:     "false",
			Description: "Snapshot whether or not the plugin will take a snapshot of the entire table before starting cdc.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigSnowflakeOrderingColumn: {
			Default:     "",
			Description: "OrderingColumn is a name of a column that the connector will use for ordering rows.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigSnowflakePrimaryKeys: {
			Default:     "",
			Description: "Primary keys",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigSnowflakeSnapshot: {
			Default:     "false",
			Description: "Snapshot",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{},
		},
		ConfigSnowflakeTable: {
			Default:     "",
			Description: "Table name.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigSnowflakeUrl: {
			Default:     "",
			Description: "Connection string connection to snowflake DB.\nDetail information https://pkg.go.dev/github.com/snowflakedb/gosnowflake@v1.6.9#hdr-Connection_String",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
