// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package source

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"snowflake.batchsize": {
			Default:     "0",
			Description: "snowflake.batchsize - size of batch.",
			Type:        sdk.ParameterTypeInt,
			Validations: []sdk.Validation{},
		},
		"snowflake.columns": {
			Default:     "",
			Description: "Snapshot whether or not the plugin will take a snapshot of the entire table before starting cdc.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"snowflake.orderingColumn": {
			Default:     "",
			Description: "snowflake.orderingColumn is a name of a column that the connector will use for ordering rows.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"snowflake.primaryKeys": {
			Default:     "",
			Description: "Primary keys",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"snowflake.snapshot": {
			Default:     "true",
			Description: "snowflake.snapshot",
			Type:        sdk.ParameterTypeBool,
			Validations: []sdk.Validation{},
		},
		"snowflake.table": {
			Default:     "",
			Description: "snowflake.table name.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"snowflake.url": {
			Default:     "",
			Description: "snowflake.url string connection to snowflake DB. Detail information https://pkg.go.dev/github.com/snowflakedb/gosnowflake@v1.6.9#hdr-snowflake.url_String",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
	}
}
